<?php

/***************************************************************
* Extension Manager/Repository config file for ext: "fal_preview"
*
* Auto generated by Extension Builder 2013-04-16
*
* Manual updates:
* Only the data in the array - anything else is removed by next write.
* "version" and "dependencies" must not be touched!
***************************************************************/

$EM_CONF[$_EXTKEY] = array (
	'title' => 'FAL "other" thumbnail/preview',
	'description' => 'Generate thumbnails for preview for any sys_file entity from another referred/associated sys_file entity',
	'category' => 'misc',
	'author' => 'Steffen Ritter',
	'author_email' => 'info@rs-websystems.de',
	'author_company' => 'RS WebSystems',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => 'uploads/fal_preview',
	'modify_tables' => 'sys_file',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.1.5',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.1',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>
